import { useState } from 'react';
import { FaPenFancy, FaFileDownload, FaMagic } from 'react-icons/fa';
// import jsPDF from 'jspdf'; // Assuming jsPDF is available or will use dynamic import

const SOPWizard = () => {
    const [step, setStep] = useState(1);
    const [answers, setAnswers] = useState({
        background: '',
        whyCourse: '',
        goals: ''
    });

    const handleNext = () => setStep(step + 1);
    const handleChange = (field, value) => setAnswers(prev => ({ ...prev, [field]: value }));

    const generateSOP = async () => {
        const { jsPDF } = await import('jspdf');
        const doc = new jsPDF();
        
        // --- Header ---
        doc.setFillColor(79, 70, 229); // Primary Color
        doc.rect(0, 0, 210, 40, 'F');
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(22);
        doc.text("Statement of Purpose Draft", 20, 20);
        doc.setFontSize(12);
        doc.text("Generated by Ambition Global Consultancy", 20, 30);
        
        const splitText = (text, y) => {
            const lines = doc.splitTextToSize(text, 170);
            doc.text(lines, 20, y);
            return y + (lines.length * 7);
        };
        
        // --- Content ---
        doc.setTextColor(33, 33, 33);
        let yPos = 60;
        
        // Background
        doc.setFontSize(14);
        doc.setTextColor(79, 70, 229);
        doc.text("1. Academic & Professional Background", 20, yPos);
        yPos += 10;
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        yPos = splitText(answers.background || "N/A", yPos);
        yPos += 10;
        
        // Why Course
        doc.setFontSize(14);
        doc.setTextColor(79, 70, 229);
        doc.text("2. Why This Course?", 20, yPos);
        yPos += 10;
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        yPos = splitText(answers.whyCourse || "N/A", yPos);
        yPos += 10;
        
        // Goals
        doc.setFontSize(14);
        doc.setTextColor(79, 70, 229);
        doc.text("3. Future Career Goals", 20, yPos);
        yPos += 10;
        doc.setFontSize(11);
        doc.setTextColor(60, 60, 60);
        yPos = splitText(answers.goals || "N/A", yPos);
        
        // --- Footer ---
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text("This is an initial draft. We recommend reviewing it with our counselors.", 105, 280, { align: "center" });
        
        doc.save('SOP_Draft_Ambition.pdf');
    };

    return (
        <div className="bg-white dark:bg-slate-800 rounded-3xl p-8 shadow-xl border border-slate-100 dark:border-slate-700 h-full">
            <h3 className="text-2xl font-bold mb-6 text-slate-800 dark:text-white flex items-center gap-2">
                <FaPenFancy className="text-secondary" /> SOP Wizard
            </h3>

            <div className="space-y-6">
                {step === 1 && (
                    <div className="animate-fade-in">
                        <label className="label font-bold text-slate-600 dark:text-slate-300">Tell us about your academic background</label>
                        <textarea 
                            className="textarea textarea-bordered w-full h-32 bg-slate-50 dark:bg-slate-700" 
                            placeholder="I completed my Bachelors in..."
                            value={answers.background}
                            onChange={(e) => handleChange('background', e.target.value)}
                        />
                         <button onClick={handleNext} className="btn btn-primary w-full mt-4">Next: Why this Course?</button>
                    </div>
                )}

                {step === 2 && (
                    <div className="animate-fade-in">
                        <label className="label font-bold text-slate-600 dark:text-slate-300">Why do you want to study this course?</label>
                        <textarea 
                            className="textarea textarea-bordered w-full h-32 bg-slate-50 dark:bg-slate-700" 
                            placeholder="I have always been passionate about..."
                            value={answers.whyCourse}
                            onChange={(e) => handleChange('whyCourse', e.target.value)}
                        />
                         <div className="grid grid-cols-2 gap-4 mt-4">
                             <button onClick={() => setStep(1)} className="btn btn-outline">Back</button>
                             <button onClick={handleNext} className="btn btn-primary">Next: Future Goals</button>
                         </div>
                    </div>
                )}

                {step === 3 && (
                    <div className="animate-fade-in">
                        <label className="label font-bold text-slate-600 dark:text-slate-300">What are your future career goals?</label>
                        <textarea 
                            className="textarea textarea-bordered w-full h-32 bg-slate-50 dark:bg-slate-700" 
                            placeholder="I plan to work as a..."
                            value={answers.goals}
                            onChange={(e) => handleChange('goals', e.target.value)}
                        />
                        <div className="grid grid-cols-2 gap-4 mt-4">
                             <button onClick={() => setStep(2)} className="btn btn-outline">Back</button>
                             <button onClick={() => setStep(4)} className="btn btn-primary">Finish</button>
                         </div>
                    </div>
                )}

                {step === 4 && (
                    <div className="text-center animate-fade-in py-8">
                        <div className="bg-secondary/10 w-20 h-20 rounded-full flex items-center justify-center mx-auto mb-4 text-secondary text-3xl">
                            <FaMagic />
                        </div>
                        <h4 className="text-xl font-bold mb-2 text-slate-800 dark:text-white">Your Draft is Ready!</h4>
                        <p className="text-slate-500 mb-6">We have structured your inputs into a professional outline.</p>
                        
                        <button onClick={generateSOP} className="btn btn-secondary w-full gap-2 text-white">
                            <FaFileDownload /> Download Draft
                        </button>
                        <button onClick={() => setStep(1)} className="btn btn-ghost btn-sm mt-4">Create New</button>
                    </div>
                )}
            </div>
            
            {/* Progress Steps */}
            <div className="flex justify-center gap-2 mt-8">
                {[1, 2, 3, 4].map(s => (
                    <div key={s} className={`h-2 w-2 rounded-full transition-colors ${s <= step ? 'bg-secondary' : 'bg-slate-200 dark:bg-slate-700'}`} />
                ))}
            </div>
        </div>
    );
};

export default SOPWizard;
